# Generated by Django 2.2.5 on 2020-02-20 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0004_log_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complain',
            name='raised',
            field=models.BooleanField(default=False),
        ),
    ]
