# Generated by Django 2.2.5 on 2020-02-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0005_complain_raised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.IntegerField(blank=True, max_length=100000, null=True),
        ),
    ]
