# Generated by Django 2.2.5 on 2020-02-20 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0006_auto_20200220_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
