# Generated by Django 2.2.5 on 2020-02-20 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_auto_20200220_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
