# Generated by Django 2.2.5 on 2020-02-20 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0008_auto_20200220_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Processing', 'Processing'), ('Solved', 'Solved'), ('Closed', 'Closed')], default='Raised', max_length=50),
        ),
    ]
